### ISSUE TITLE
'jsr wait' in readme example

### ISSUE THREAD

**Issue by sajattack** [cliffordcarnmo/c64-devkit#1]
Shouldn't this be jmp wait? Because wait is a label not a subroutine

**Comment by cliffordcarnmo** [comment]
Thanks for your input and sorry for the delay in answering. I just realised your issue existed. Regarding your issue you are partly correct. JSR saves the return address and enables you to return to the same place using RTS. A label is just a human-readable version of a memory address, it could just as well have been a hexadecimal number. Since my code obviously is buggy and should use a JMP, I tip my hat to you dear sir and just updated the source to reflect this.
